---
abstract: 'Object-oriented access to real and tied hashes'
author:
  - 'Nat Goodman <natg@shore.net>'
build_requires:
  Exporter: 5.58
  Test::Deep: 0.11
  Test::More: 0.88
  Tie::Hash::MultiValue: 0
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hash-AutoHash
provides:
  Hash::AutoHash:
    file: lib/Hash/AutoHash.pm
    version: 1.16
  Hash::AutoHash::alias:
    file: lib/Hash/AutoHash.pm
    version: 0
  Hash::AutoHash::helper:
    file: lib/Hash/AutoHash.pm
    version: 0
requires:
  Carp: 0
  List::MoreUtils: 0.09
  Scalar::Util: 1.01
  Tie::Hash: 1
  Tie::ToObject: 0
  perl: v5.8.3
resources:
  license: http://dev.perl.org/licenses/
version: 1.16
